import { Inter } from "next/font/google";
import "../../globals.css";
import AdminHeader from "@/app/components/AdminHeader";
import Link from "next/link";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin Panel of book shop",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <>
       <AdminHeader/>
       <div className="flex px-[7%] mt-5 ">
        <div className="w-1/4">
          <div className="flex flex-col rounded ">
          <Link href="/admin" className=" text-black bg-gray-500 hover:bg-gray-700 px-4 py-3">Dashboard</Link>
          <Link href="/admin/category" className=" text-black bg-gray-500 hover:bg-gray-700 px-4 py-3">Manage Category</Link>
          <Link href="/admin/users" className=" text-black bg-gray-500 hover:bg-gray-700 px-4 py-3"> Manage User</Link>
          <Link href="/admin/book" className=" text-black bg-gray-500 hover:bg-gray-700 px-4 py-3"> Manage Book </Link>
          <Link href="/admin/orders" className=" text-black bg-gray-500 hover:bg-gray-700 px-4 py-3">Manage Order </Link>
          <Link href="" className=" text-black bg-gray-500 hover:bg-gray-700 px-4 py-3">Manage Pament  </Link>
          <Link href="/login" className=" text-black bg-gray-500 hover:bg-gray-700 px-4 py-3">Login </Link>
          <Link href="" className=" text-black bg-gray-500 hover:bg-gray-700 px-4 py-3">Logout </Link>
          </div>
        </div>
        <div className="w-3/4">
          {children}
          <Toaster position="top-right"/>
        </div>
       </div>
    </>
  );
}